language: cpp

compiler:
 - gcc

before_script:
 - sudo apt-add-repository --yes ppa:ubuntu-sdk-team/ppa
 - sudo apt-get update -qq > output
 - sudo apt-get install -qq qt5-default libqt5svg5-dev > output
 - cd viewer
 - mkdir build
 - cd build
 - wget http://www.cmake.org/files/v2.8/cmake-2.8.12.1-Linux-i386.tar.gz
 - tar xzf cmake-2.8.12.1-Linux-i386.tar.gz
 - `pwd`/cmake-2.8.12.1-Linux-i386/bin/cmake ../

script: make
