language: cpp

compiler:
 - gcc

before_script:
 - wget https://launchpad.net/ubuntu/+archive/primary/+files/cmake_2.8.12.1.orig.tar.gz
 - tar xvzf cmake_2.8.12.1.orig.tar.gz
 - cd cmake-2.8.12.1
 - mkdir build
 - cd build
 - cmake ..
 - make
 - echo " CMake version before installing the new one: "
 - cmake --version
 - sudo make install
 - echo " CMake version after installing the new one: "
 - cmake --version 
 - sudo apt-add-repository --yes ppa:ubuntu-sdk-team/ppa
 - sudo apt-get update -qq
 - sudo apt-get install -qq qt5-default
 - cd ../../
 - cd viewer
 - mkdir build
 - cd build
 - cmake ..

script: make
