language: cpp

compiler:
 - gcc

before_script:
 - wget https://launchpad.net/ubuntu/+archive/primary/+files/cmake_2.8.12.1.orig.tar.gz
 - tar xzf cmake_2.8.12.1.orig.tar.gz
 - cd cmake-2.8.12.1
 - mkdir build
 - cd build
 - cmake ..
 - cmake --version
 - make
 - sudo make install
 - cmake --version
 - /usr/local/bin/cmake --version
 - sudo apt-add-repository --yes ppa:ubuntu-sdk-team/ppa
 - sudo apt-get update -qq > output
 - sudo apt-get install -qq qt5-default > output
 - cd ../../
 - cd viewer
 - mkdir build
 - cd build
 - /usr/local/bin/cmake ..

script: make
