language: cpp

compiler:
 - gcc

before_script:
 - sudo apt-add-repository ppa:ubuntu-sdk-team/ppa
 - sudo apt-get update -qq
 - sudo apt-get install -qq qt5-default
 - cd viewer
 - mkdir build
 - cd build
 - cmake ..

script: make
