language: cpp
sudo: required
dist: trusty

compiler:
 - gcc
 - clang

before_install:
 - if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-add-repository --yes ppa:ubuntu-sdk-team/ppa; fi
 - if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get update -qq > output; fi
 - if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get install -qq qt5-default libqt5svg5-dev cmake > output; fi
 - if [ $TRAVIS_OS_NAME == osx ]; then brew update && brew install qt5 && export PATH=/usr/local/opt/qt5/bin:$PATH; fi

before_script:
 - cd viewer
 - mkdir build
 - cd build
 - cmake --version
 - cmake ../

script: make

os:
 - linux
 - osx

# Exclude the clang on Linux combination: Qt 5.0 headers generates errors with clang
matrix:
  exclude:
   - compiler: clang
     os: linux